# SETTINGS
app:
  external-url: http://localhost:8081
server:
  port: 8081

#GENERAL
spring:
  application.name: bootdb

#DATA SOURCE
  datasource:
    hikari.pool-name: bootdb
    hikari.maximum-pool-size: 3
    source: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres123

#JPA
  jpa:
    #hibernate.ddl-auto: create
    hibernate.ddl-auto: validate
    show-sql: true
    open-in-view: true



